spring:
  application:
    name: unit-test-tracker

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  elasticsearch:
      uris: http://localhost:9200

server:
  port: 8083

logging:
  level:
    root: INFO
    com.sprinklr.unittesttracker: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

github:
  token: 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