spring:
  application:
    name: unit-test-tracker

  elasticsearch:
      uris: http://localhost:9200
      username: elastic
      password: ZfJ9IeSao=*DuBloQzK-
server:
  port: 8080

logging:
  level:
    root: INFO
    com.sprinklr.unittesttracker: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"